name: Playwright Tests

# Add workflow_dispatch to trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Set up environment variables from GitHub Secrets
    - name: Set environment variables from secrets
      run: |
        echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
        echo "PASSWORD_WPC=${{ secrets.PASSWORD_WPC }}" >> $GITHUB_ENV
        echo "AD_EMAIL=${{ secrets.AD_EMAIL }}" >> $GITHUB_ENV
        echo "PHONE=${{ secrets.PHONE }}" >> $GITHUB_ENV

    # Debug Environment Variables
    - name: Debug Environment Variables
      run: |
        echo "Email: ${{ secrets.EMAIL }}"
        echo "Password: ${{ secrets.PASSWORD_WPC }}"

    - name: Run Playwright tests
      run: npx playwright test
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD_WPC: ${{ secrets.PASSWORD_WPC }}
        AD_EMAIL: ${{ secrets.AD_EMAIL }}
        PHONE: ${{ secrets.PHONE }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30